# GKTickets - Configurazione

# Impostazioni del database
database:
  # Tipo di database (supportato: sqlite)
  type: sqlite
  # Nome del file del database
  name: tickets

# Impostazioni dei ticket
tickets:
  # Numero massimo di ticket aperti per utente (0 = illimitato)
  max-per-user: 3
  
  # Impostazioni per la chiusura automatica dei ticket
  auto-close:
    # Abilita la chiusura automatica dei ticket inattivi
    enabled: true
    # Tempo in ore dopo il quale un ticket inattivo viene chiuso automaticamente
    time: 72
    # Messaggio di chiusura automatica
    message: "Ticket chiuso automaticamente dopo {hours} ore di inattività"
    # Invia una notifica al giocatore quando il suo ticket viene chiuso automaticamente
    notify-player: true
    # Categorie esenti dalla chiusura automatica (lista)
    exempt-categories: 
      - importante
      - urgente
    # Ore prima della chiusura per l'invio di un avviso
    warning-time: 48
    # Inviare un avviso prima della chiusura automatica
    send-warning: true

# Integrazione Discord
discord:
  # Abilita l'integrazione con Discord
  enabled: false
  # URL del webhook Discord
  webhook-url: "https://discord.com/api/webhooks/your-webhook-url-here"
  # Nome utente del bot che invia i messaggi
  username: "GKTickets"
  # URL dell'avatar del bot
  avatar-url: "https://i.imgur.com/your-avatar.png"
  # Eventi da loggare
  log-events:
    # Log alla creazione di un nuovo ticket
    ticket-create: true
    # Log alla chiusura di un ticket
    ticket-close: true
    # Log quando viene aggiunta una risposta
    ticket-reply: true
  # Colori degli embed per diversi tipi di eventi (esadecimale)
  colors:
    create: "#00FF00"  # Verde
    reply: "#0099FF"   # Blu
    close: "#FF0000"   # Rosso

# Impostazioni delle notifiche
notifications:
  # Notifiche per lo staff
  staff:
    # Notifica lo staff quando viene creato un nuovo ticket
    new-ticket: true
    # Notifica lo staff quando viene aggiunta una risposta ad un ticket
    new-reply: true

  # Notifiche per i giocatori
  player:
    # Notifica al giocatore quando viene aggiunta una risposta al suo ticket
    new-reply: true
    # Notifica al giocatore quando il suo ticket viene chiuso
    ticket-closed: true

  # Impostazioni dei suoni
  sound:
    # Abilita i suoni per le notifiche
    enabled: true
    # Suono per i nuovi ticket
    new-ticket: entity.experience_orb.pickup
    # Suono per le nuove risposte
    new-reply: entity.player.levelup

# Permessi
permissions:
  # Impostazione di gestione ticket 
  # Se true, i giocatori possono visualizzare e rispondere solo ai propri ticket
  # Se false, i giocatori possono visualizzare e rispondere a qualsiasi ticket con il permesso appropriato
  player-only-own-tickets: true

# Configurazioni per i feedback
feedback:
  enabled: true
  # Intervallo in minuti tra i promemoria feedback (0 per disabilitare)
  reminder-interval: 30

# Blacklist configuration
blacklist:
  enabled: true
  # Default expiry time in days (0 = permanent)
  default-expiry: 7

# Reporting configuration
reporting:
  enabled: false
  webhook-url: "" # Your Discord webhook URL for reports
  username: "GKTickets Reporter"
  avatar-url: "https://i.imgur.com/YourLogoHere.png"
  # Types of reports to send
  report-types:
    blacklist: true
    ticket-stats: true
  # Hours between stats reports (0 to disable periodic stats)
  stats-interval: 24
  # Colors for different report types (hex color codes)
  colors:
    blacklist: "#FF0000" # Red
    stats: "#00FFFF"     # Cyan
