name: GKTickets
version: '1.0'
main: it.giankoyt.gktickets.GKTickets
api-version: '1.21'
authors: [GiankoYT]
description: Sistema di ticket con SQLite e notifiche per Minecraft 1.21.4
commands:
  ticket:
    description: Comando principale per la gestione dei ticket
    usage: /ticket <create|list|info|close|reply> [argomenti]
    aliases: [tickets, tk]
permissions:
  gktickets.create:
    description: Permette di creare ticket
    default: true
  gktickets.view:
    description: Permette di visualizzare i propri ticket
    default: true
  gktickets.staff:
    description: Permette allo staff di gestire tutti i ticket
    default: op
