name: GKTickets
version: 1.0.2
main: it.Gecky.gktickets.GKTickets
api-version: 1.13
softdepend: [PlaceholderAPI]
authors: [gecky2102]
description: A simple ticket system plugin for Bukkit/Spigot servers

commands:
  ticket:
    description: Comando principale per la gestione dei ticket
    aliases: [tk]
    usage: /ticket <create|list|info|close|reply> [argomenti]

permissions:
  gktickets.*:
    description: Accesso a tutti i comandi e funzionalità di GKTickets
    default: op
    children:
      gktickets.staff: true
      gktickets.admin: true
      gktickets.create: true
      gktickets.view: true
      gktickets.list: true
      gktickets.info: true
      gktickets.close: true
      gktickets.close.own: true
      gktickets.close.others: true
      gktickets.reply: true
  
  gktickets.staff:
    description: Accesso alle funzionalità di staff
    default: op
    children:
      gktickets.view: true
      gktickets.list: true
      gktickets.info: true
      gktickets.close.others: true
      gktickets.reply: true
  
  gktickets.admin:
    description: Accesso alle funzionalità di amministrazione
    default: op
    
  gktickets.create:
    description: Permesso per creare ticket
    default: true
    
  gktickets.view:
    description: Permesso per visualizzare i propri ticket
    default: true
    
  gktickets.list:
    description: Permesso per elencare ticket
    default: true
    
  gktickets.info:
    description: Permesso per visualizzare informazioni dettagliate sui ticket
    default: true
    
  gktickets.close:
    description: Permesso di base per chiudere i ticket
    default: false
    children:
      gktickets.close.own: true
      
  gktickets.close.own:
    description: Permesso per chiudere i propri ticket
    default: true
    
  gktickets.close.others:
    description: Permesso per chiudere i ticket di altri giocatori
    default: op
    
  gktickets.reply:
    description: Permesso per rispondere ai ticket
    default: true
